name: Publish to PyPI (Trusted Publisher)

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build backend
        run: python -m pip install --upgrade pip build

      - name: Build dist
        run: python -m build

      - name: Publish to PyPI via OIDC
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # if you also want TestPyPI, add repository-url here for a separate job
          # repository-url: https://test.pypi.org/legacy/
          # skip-existing: true
          verbose: true
